services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    command: gunicorn safeproj.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume_prod:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./envs/.env.prod
    depends_on:
      - db
  db:
    image: postgres:16.4-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./envs/.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume_prod:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data_prod:
  static_volume_prod:
